spring:
  application:
    name: wallet
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost/wallet_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
  config:
    import: classpath:secrets.properties
server:
  port: 8081
  servlet:
    context-path: /auth
app:
  keycloak:
    realm: wallet
    serverUrl: http://localhost:8085